dotnet sln add C:\Dev\z0\src\agents\z0.agents.csproj
dotnet sln add C:\Dev\z0\src\api\z0.api.csproj
dotnet sln add C:\Dev\z0\src\apps\z0.apps.csproj
dotnet sln add C:\Dev\z0\src\asci\z0.asci.csproj
dotnet sln add C:\Dev\z0\src\asm\z0.asm.csproj
dotnet sln add C:\Dev\z0\src\asm.cases\z0.asm.cases.csproj
dotnet sln add C:\Dev\z0\src\asm.catalogs\z0.asm.catalogs.csproj
dotnet sln add C:\Dev\z0\src\asm.core\z0.asm.core.csproj
dotnet sln add C:\Dev\z0\src\asm.lang\z0.asm.lang.csproj
dotnet sln add C:\Dev\z0\src\asm.lang.g\z0.asm.lang.g.csproj
dotnet sln add C:\Dev\z0\src\asm.run\z0.asm.run.csproj
dotnet sln add C:\Dev\z0\src\asmz\z0.asmz.csproj
dotnet sln add C:\Dev\z0\src\bitfields\z0.bitfields.csproj
dotnet sln add C:\Dev\z0\src\bitfields.shell\z0.bitfields.shell.csproj
dotnet sln add C:\Dev\z0\src\bitgrids\z0.bitgrids.csproj
dotnet sln add C:\Dev\z0\src\bitmasks\z0.bitmasks.csproj
dotnet sln add C:\Dev\z0\src\bitmatrix\z0.bitmatrix.csproj
dotnet sln add C:\Dev\z0\src\bitnumbers\z0.bitnumbers.csproj
dotnet sln add C:\Dev\z0\src\bitnumbers.shell\z0.bitnumbers.shell.csproj
dotnet sln add C:\Dev\z0\src\bitpack\z0.bitpack.csproj
dotnet sln add C:\Dev\z0\src\bits\z0.bits.csproj
dotnet sln add C:\Dev\z0\src\bitspans\z0.bitspans.csproj
dotnet sln add C:\Dev\z0\src\bitstrings\z0.bitstrings.csproj
dotnet sln add C:\Dev\z0\src\bitvectors\z0.bitvectors.csproj
dotnet sln add C:\Dev\z0\src\calc\z0.calc.csproj
dotnet sln add C:\Dev\z0\src\calc.shell\z0.calc.shell.csproj
dotnet sln add C:\Dev\z0\src\canonical\z0.canonical.csproj
dotnet sln add C:\Dev\z0\src\capture\z0.capture.csproj
dotnet sln add C:\Dev\z0\src\capture.checks\z0.capture.checks.csproj
dotnet sln add C:\Dev\z0\src\check\z0.check.csproj
dotnet sln add C:\Dev\z0\src\circuits\z0.circuits.csproj
dotnet sln add C:\Dev\z0\src\cli\z0.cli.csproj
dotnet sln add C:\Dev\z0\src\clr\z0.clr.csproj
dotnet sln add C:\Dev\z0\src\control\z0.control.csproj
dotnet sln add C:\Dev\z0\src\core\z0.core.csproj
dotnet sln add C:\Dev\z0\src\cpu\z0.cpu.csproj
dotnet sln add C:\Dev\z0\src\cpu.dsl\z0.cpu.dsl.csproj
dotnet sln add C:\Dev\z0\src\cpu.shell\z0.cpu.shell.csproj
dotnet sln add C:\Dev\z0\src\digital\z0.digital.csproj
dotnet sln add C:\Dev\z0\src\dynamic\z0.dynamic.csproj
dotnet sln add C:\Dev\z0\src\dynamic.shell\z0.dynamic.shell.csproj
dotnet sln add C:\Dev\z0\src\evaluate\z0.evaluate.csproj
dotnet sln add C:\Dev\z0\src\events\z0.events.csproj
dotnet sln add C:\Dev\z0\src\external\z0.external.csproj
dotnet sln add C:\Dev\z0\src\extract\z0.extract.csproj
dotnet sln add C:\Dev\z0\src\fsm\z0.fsm.csproj
dotnet sln add C:\Dev\z0\src\gather\z0.gather.csproj
dotnet sln add C:\Dev\z0\src\gen\z0.gen.csproj
dotnet sln add C:\Dev\z0\src\gen.shell\z0.gen.shell.csproj
dotnet sln add C:\Dev\z0\src\gmath\z0.gmath.csproj
dotnet sln add C:\Dev\z0\src\interop\z0.interop.csproj
dotnet sln add C:\Dev\z0\src\lang\z0.lang.csproj
dotnet sln add C:\Dev\z0\src\logix\z0.logix.csproj
dotnet sln add C:\Dev\z0\src\machine\z0.machine.csproj
dotnet sln add C:\Dev\z0\src\math\z0.math.csproj
dotnet sln add C:\Dev\z0\src\minidump\z0.minidump.csproj
dotnet sln add C:\Dev\z0\src\nats\z0.nats.csproj
dotnet sln add C:\Dev\z0\src\part\z0.part.csproj
dotnet sln add C:\Dev\z0\src\pipes\z0.pipes.csproj
dotnet sln add C:\Dev\z0\src\polysource\z0.polysource.csproj
dotnet sln add C:\Dev\z0\src\related\z0.related.csproj
dotnet sln add C:\Dev\z0\src\res\z0.res.csproj
dotnet sln add C:\Dev\z0\src\respack\z0.respack.csproj
dotnet sln add C:\Dev\z0\src\root\z0.root.csproj
dotnet sln add C:\Dev\z0\src\run\z0.run.csproj
dotnet sln add C:\Dev\z0\src\services\z0.services.csproj
dotnet sln add C:\Dev\z0\src\sfuncs\z0.sfuncs.csproj
dotnet sln add C:\Dev\z0\src\spanblocks\z0.spanblocks.csproj
dotnet sln add C:\Dev\z0\src\stats\z0.stats.csproj
dotnet sln add C:\Dev\z0\src\symbolic\z0.symbolic.csproj
dotnet sln add C:\Dev\z0\src\sys\z0.sys.csproj
dotnet sln add C:\Dev\z0\src\tables\z0.tables.csproj
dotnet sln add C:\Dev\z0\src\term\z0.term.csproj
dotnet sln add C:\Dev\z0\src\tooling\z0.tooling.csproj
dotnet sln add C:\Dev\z0\src\tools\z0.tools.csproj
dotnet sln add C:\Dev\z0\src\tools.shell\z0.tools.shell.csproj
dotnet sln add C:\Dev\z0\src\validity\z0.validity.csproj
dotnet sln add C:\Dev\z0\src\workers\z0.workers.csproj
dotnet sln add C:\Dev\z0\src\workflow\z0.workflow.csproj
dotnet sln add C:\Dev\z0\src\xed\z0.xed.csproj
