del j:\dev\projects\z0\native\libm\z0.libm.xml
del j:\dev\projects\z0\native\mkl\src\z0.mkl.xml
del j:\dev\projects\z0\native\mkl\test\z0.mkl.test.xml
del j:\dev\projects\z0\src\apps\z0.apps.xml
del j:\dev\projects\z0\src\asm\z0.asm.xml
del j:\dev\projects\z0\src\asm.code\z0.asm.code.xml
del j:\dev\projects\z0\src\asm.models\z0.asm.models.xml
del j:\dev\projects\z0\src\bitcore\z0.bitcore.xml
del j:\dev\projects\z0\src\bitfields\z0.bitfields.xml
del j:\dev\projects\z0\src\bitgrids\z0.bitgrids.xml
del j:\dev\projects\z0\src\bitmasks\z0.bitmasks.xml
del j:\dev\projects\z0\src\bitmatrix\z0.bitmatrix.xml
del j:\dev\projects\z0\src\bitpack\z0.bitpack.xml
del j:\dev\projects\z0\src\bits\z0.bits.xml
del j:\dev\projects\z0\src\bitspans\z0.bitspans.xml
del j:\dev\projects\z0\src\bitstrings\z0.bitstrings.xml
del j:\dev\projects\z0\src\bitsvc\z0.bitsvc.xml
del j:\dev\projects\z0\src\bitvectors\z0.bitvectors.xml
del j:\dev\projects\z0\src\blocked\z0.blocked.xml
del j:\dev\projects\z0\src\blocks\z0.blocks.xml
del j:\dev\projects\z0\src\canonical\z0.canonical.xml
del j:\dev\projects\z0\src\capture\z0.capture.xml
del j:\dev\projects\z0\src\cil\z0.cil.xml
del j:\dev\projects\z0\src\circuits\z0.circuits.xml
del j:\dev\projects\z0\src\control\z0.control.xml
del j:\dev\projects\z0\src\data\z0.data.xml
del j:\dev\projects\z0\src\domain\z0.domain.xml
del j:\dev\projects\z0\src\dvec\z0.dvec.xml
del j:\dev\projects\z0\src\dynamic\z0.dynamic.xml
del j:\dev\projects\z0\src\evaluate\z0.evaluate.xml
del j:\dev\projects\z0\src\expressive\z0.expressive.xml
del j:\dev\projects\z0\src\extract\z0.extract.xml
del j:\dev\projects\z0\src\fixed\z0.fixed.xml
del j:\dev\projects\z0\src\flow\z0.flow.xml
j:\dev\projects\z0\src\flow\src\support\synthesis\z0.respack.xml
del j:\dev\projects\z0\src\fvec\z0.fvec.xml
del j:\dev\projects\z0\src\gmath\z0.gmath.xml
del j:\dev\projects\z0\src\gvec\z0.gvec.xml
del j:\dev\projects\z0\src\identify\z0.identify.xml
del j:\dev\projects\z0\src\identity\z0.identity.xml
del j:\dev\projects\z0\src\imagine\z0.imagine.xml
del j:\dev\projects\z0\src\json\z0.json.xml
del j:\dev\projects\z0\src\kinds\z0.kinds.xml
del j:\dev\projects\z0\src\konst\z0.konst.xml
del j:\dev\projects\z0\src\lang\z0.lang.xml
del j:\dev\projects\z0\src\logix\z0.logix.xml
del j:\dev\projects\z0\src\lsquare\z0.lsquare.xml
del j:\dev\projects\z0\src\machine\z0.machine.xml
del j:\dev\projects\z0\src\math\z0.math.xml
del j:\dev\projects\z0\src\mathsvc\z0.mathsvc.xml
del j:\dev\projects\z0\src\matrix\z0.matrix.xml
del j:\dev\projects\z0\src\memories\z0.memories.xml
del j:\dev\projects\z0\src\metareader\z0.metareader.xml
del j:\dev\projects\z0\src\monitor\z0.monitor.xml
del j:\dev\projects\z0\src\nats\z0.nats.xml
del j:\dev\projects\z0\src\numeric\z0.numeric.xml
del j:\dev\projects\z0\src\part\z0.part.xml
del j:\dev\projects\z0\src\polyrand\z0.polyrand.xml
del j:\dev\projects\z0\src\run\z0.run.xml
del j:\dev\projects\z0\src\seed\z0.seed.xml
del j:\dev\projects\z0\src\stats\z0.stats.xml
del j:\dev\projects\z0\src\structured\z0.structured.xml
del j:\dev\projects\z0\src\symbolic\z0.symbolic.xml
del j:\dev\projects\z0\src\sys\z0.sys.xml
del j:\dev\projects\z0\src\tool.cli\z0.tool.cli.xml
del j:\dev\projects\z0\src\tool.core\z0.tool.core.xml
del j:\dev\projects\z0\src\v0\z0.v0.xml
del j:\dev\projects\z0\src\validity\z0.validity.xml
del j:\dev\projects\z0\src\vbits\z0.vbits.xml
del j:\dev\projects\z0\src\vcheck\z0.vcheck.xml
del j:\dev\projects\z0\src\vdata\z0.vdata.xml
del j:\dev\projects\z0\src\vectors\z0.vectors.xml
del j:\dev\projects\z0\src\vsvc\z0.vsvc.xml
del j:\dev\projects\z0\src\win\z0.win.xml
del j:\dev\projects\z0\src\zxed\z0.zxed.xml
del j:\dev\projects\z0\test\asm\z0.asm.test.xml
del j:\dev\projects\z0\test\asmd\z0.asmd.test.xml
del j:\dev\projects\z0\test\bits\z0.bits.test.xml
del j:\dev\projects\z0\test\dynamic\z0.dynamic.test.xml
del j:\dev\projects\z0\test\gvec\z0.gvec.test.xml
del j:\dev\projects\z0\test\identity\z0.identity.test.xml
del j:\dev\projects\z0\test\logix\z0.logix.test.xml
del j:\dev\projects\z0\test\machines\z0.machines.test.xml
del j:\dev\projects\z0\test\math\z0.math.test.xml
del j:\dev\projects\z0\test\symbolic\z0.symbolic.test.xml