tool = ildasm;

command = tool options <file_name>;

option = /Flag[args];

options = [option...];

specifier = "=";

metadaa_choice = 
      MDHEADER 
    | HEX 
    | CSV 
    | UNREX 
    | SCHEMA 
    | RAW 
    | HEAPS 
    | VALIDATE;

vis = 
     PUB 
   | PRI 
   | FAM 
   | ASM 
   | FAA 
   | FOA 
   | PSC;          

Flag = 
      OUT[specifier, <file_name>]  
    | TEXT  
    | HTML 
    | RTF 
    | BYTES 
    | RAWEH 
    | TOKENS 
    | SOURCE 
    | LINENUM 
    | VISIBILITY, specifier, vis [vis...]
    | PUBONLY 
    | QUOTEALLNAMES 
    | NOCA 
    | CAVERBAL 
    | NOBAR
    | UTF8
    | UNICODE
    | NOIL
    | FORWARD
    | TYPELIST
    | PROJECT
    | HEADERS
    | ITEM
    | STATS
    | CLASSLIST
    | ALL        
    | METADATA [specifier, metadaa_choice]
    | OBJECTFILE;